### ISSUE TITLE
System-wide debug symbols not used by default

### ISSUE THREAD

**Issue by loskutov** [KDAB/hotspot#128]
Having the `libc6-dbg` package installed in my Ubuntu 18.04 system, I still don't see any function names inside libc unless I specify the path to debug symbols explicitly with `--debugPaths /usr/lib/debug`. However, this path is somewhat standard, and discussion under #52 implies it's already in the default search path, which doesn't seem to be the case. I'm using the 1.1.0 AppImage distribution.

UPD: it looks like the issue is only present when using AppImage; anyway, the binary built from master doesn't need explicit paths.

**Comment by milianw** [comment]
maybe it's just something that got fixed in the meantime - can you try the latest appimage from here please: https://transfer.sh/akdxR/Hotspot-git.d561618-x86_64.AppImage

**Comment by loskutov** [comment]
It seems like it

**Comment by battaglia01** [comment]
FYI, I still have this problem, and I compiled HotSpot yesterday (June 9, 2018) from the latest Github commit. I get the following:

```
Failed to parse kernel symbol mapping file "//proc/kallsyms": Mapping is empty.
Module "[kernel.kallsyms]_text" is missing (some) debug symbols.
Module "ld-2.23.so" is missing (some) debug symbols.
Failed to find ELF file for an instruction pointer address. This can break stack unwinding and lead to missing symbols.
Module "libc-2.23.so" is missing (some) debug symbols.
Module "libstdc++.so.6.0.21" is missing (some) debug symbols.
Module "[stack]" is missing (some) debug symbols.
Could not find ELF file for anon. This can break stack unwinding and lead to missing symbols.
Module "anon" is missing (some) debug symbols.
Module "[heap]" is missing (some) debug symbols.
Module "libm-2.23.so" is missing (some) debug symbols.
Module "MYPROJECTNAME" is missing (some) debug symbols.
Module "i915.ko" is missing (some) debug symbols.
```

Note that "//proc/kallsyms" -- I'm not sure where the double slash comes from in the beginning, may be a typo somewhere. The file "/proc/kallsyms" exists on my machine and is definitely not empty.

Now, if I add a bunch of stuff explicitly to --debugPaths, such as

```
hotspot --debugPaths /usr/lib:/usr/lib/debug:/usr/lib/debug/lib:/usr/lib/debug/lib/x86_64-linux-gnu/:/usr/lib/:/usr/lib/:~/.debug/usr/lib/:~/.debug
```

then the errors for `ld-2.23.so`, `libc-2.23.so`, and `libm-2.23.so` do not appear. The other 10 errors still do appear, and in particular the error for `libstdc++.so.6.0.21`, which I'm still not sure how to fix.and I'm still not sure how to fix that.

Brendan Gregg's [FlameGraph](https://github.com/brendangregg/FlameGraph) tools for perf seem to resolve many of the missing functions, particularly the ones in the kernel -- some examples of function names it resolves are `native_irq_return_iret`, `page_fault`, `swapgs_restore_regs_and_return_to_usermode`, `error_entry` and so on. I'm not sure if it catches any from libc or libstdc++.

**Comment by battaglia01** [comment]
To add, most of the symbols seem to be there; it's only a few missing. FlameGraph does seem to catch most of the missing symbols from libc (`__run_exit_handlers`, `__memset_avx2`) and libm (`__floor_sse41`, `__ceil_sse_41`). Many of the missing symbols occur in various low-level subroutines for classes like std::vector and std::unordered_set. FlameGraph does also miss the one or two missing symbols from libstdc++, so this may be a configuration issue on my end.

I'm running KDE Neon (based on Ubuntu Trusty), for reference. I have the packges `libc6-dbg` and `libc++6-dbg` installed.

**Comment by milianw** [comment]
Let's reopen this then and we'll have to inspect this again.

**Comment by raphinesse** [comment]
I can confirm that I also have to run hotspot with `--debugPaths /usr/lib/debug` for proper symbol resolution on Ubuntu 19.10. Curiously it does not work properly when explicitly specifying `hotspot-perfparser`'s default of `--debugPaths "/usr/lib/debug:$HOME/.debug:.debug"` which, to my understanding, should look in `/usr/lib/debug` first.

The warning `Failed to parse kernel symbol mapping file "//proc/kallsyms": Mapping is empty.` is not directly related to this issue but rather a permission problem AFAICT.

> Note that `//proc/kallsyms` -- I'm not sure where the double slash comes from in the beginning, may be a typo somewhere.

I can confirm that `hotspot-perfparser` produces these double-slash paths (it probably just concats `sysroot` and `/proc/kallsyms` in this case). However, this path resolves just fine: try running `head //proc/kallsyms` for example.

> The file `/proc/kallsyms` exists on my machine and is definitely not empty.

For security reasons, `/proc/kallsyms` is redacted (all addresses are replaced by `0`) for unprivileged users. This causes aforementioned warning. A way to fix this (without running as root) is described in this [SO answer](https://stackoverflow.com/a/63213886/380229):

```
$ echo 0 | sudo tee /proc/sys/kernel/kptr_restrict > /dev/null
$ echo 0 | sudo tee /proc/sys/kernel/perf_event_paranoid > /dev/null
```

**Comment by raphinesse** [comment]
I further investigated this issue on an Ubuntu 19.10 machine and these are my findings:

Firstly, the issue is with `hotspot-perfparser`, not `hotspot` itself. To confirm that, I ran the `perf2text` tool (which calls `perfparser`) on some `perf.data` file and checked the output for symbols from `ld-2.30.so`:

```
$ perf2text --input perf.data | grep '/ld-2\.30\.so'
# Outputs mostly unresolved symbols

$ perf2text --input perf.data --debug /usr/lib/debug | grep '/ld-2\.30\.so'
# Outputs mostly resolved symbols
```

The default value for `--debug` is `/usr/lib/debug:$HOME/.debug:.debug`. `perfparser` adds a few other paths to this, then configures `libdw` with a `debuginfo_path` of `:/usr/lib/debug:$HOME/.debug:.debug:::/`. Apparently the presence of `$HOME/.debug` in the debug path is what makes the difference here. This is the location where `perf` dumps its build-id files by default.

I'm not in a position to suggest a fix for this, but here's the change in behavior I observed, depending on the presence of `$HOME/.debug` in the debug path:

*With* `$HOME/.debug`  in the debug path `PerfSymbolTable::findDebugInfo` is called with
```
moduleName = ld-2.30.so
file       = $HOME/.debug/lib/x86_64-linux-gnu/ld-2.30.so/77e4f8848d507e9563877a6819a74e53fa6f8ce2/elf
debugLink  = ld-2.30.so
```
and resolves to `/lib/x86_64-linux-gnu/ld-2.30.so` via `PerfSymbolTable::findDebugInfoFile`.

*Without* `$HOME/.debug`  in the debug path `PerfSymbolTable::findDebugInfo` is called with
```
moduleName = ld-2.30.so
file       = /lib/x86_64-linux-gnu/ld-2.30.so
debugLink  = ld-2.30.so
```
and resolves to `/usr/lib/debug/lib/x86_64-linux-gnu/ld-2.30.so` via `dwfl_standard_find_debuginfo`.

I hope this will be useful to someone.

---

PS: `perf report` properly resolves all symbols with my current setup, so it might be worth to take a look at the strategy `perf` is using. AFAICT this is done in https://github.com/torvalds/linux/blob/bcf876870b95592b52519ed4aafcf9d95999bc9c/tools/perf/util/probe-finder.c#L115-L128

**Comment by milianw** [comment]
thanks, that's interesting and useful input - we'll have to add some kind of fallback to find the debuginfo when we look into the cached data in `~/.debug` which apparently doesn't contain the debuglink file :(
