### ISSUE TITLE
Submodule ref is bugged. 

### ISSUE THREAD

**Issue by bartoszek** [KDAB/hotspot#211]
In commit 58da1c7a7607baa2cdbae7328aeacf0af4368fa2 submodule `perfparser` SHA-1 references a commit that is an orphaned reference in https://github.com/KDAB/perfparser
`git show 58da1c 3rdparty/perfparser`
```diff
commit 58da1c7a7607baa2cdbae7328aeacf0af4368fa2
Author: Milian Wolff <milian.wolff@kdab.com>
Date:   Fri Aug 9 11:25:50 2019 +0200

    update perfparser and build perf2text helper

diff --git a/3rdparty/perfparser b/3rdparty/perfparser
index 5d3f4c5..b1a5045 160000
--- a/3rdparty/perfparser
+++ b/3rdparty/perfparser
@@ -1 +1 @@
-Subproject commit 5d3f4c587eb72a668c6f667b307c7fc72108b7e5
+Subproject commit b1a504575896d3e615eac0727c3d1f17733ec9ae
```
`git submodule update --init --recursive`
```
Submodule '3rdparty/perfparser' (https://github.com/KDAB/perfparser.git) registered for path '3rdparty/perfparser'
Cloning into '/tmp/hotspot-git/src/hotspot/3rdparty/perfparser'...
error: Server does not allow request for unadvertised object b1a504575896d3e615eac0727c3d1f17733ec9ae
Fetched in submodule path '3rdparty/perfparser', but it did not contain b1a504575896d3e615eac0727c3d1f17733ec9ae. Direct fetching of that commit failed.
```

**Comment by milianw** [comment]
lessons learned, sorry for that. I just pushed an update - hope it's resolved now

**Comment by bartoszek** [comment]
The same problem is back. current ref [0cdaacb32cbcab57226bc6c96ce01c8958456122](https://github.com/KDAB/perfparser/commit/0cdaacb32cbcab57226bc6c96ce01c8958456122) is missing in `perfparser`

**Comment by milianw** [comment]
should be fixed again now, I just pushed that commit to the kdab fork. please try again and thanks for letting me know!
